const GUESTS = [
{ name: "Jane Smith", seats: 3 },
{ name: "Bobby Jurewicz", seats: 2 },
{ name: "Dale and Francine Lasky", seats: 2 },
{ name: "Pam King", seats: 1 },
{ name: "Jenn Newman", seats: 1 },
{ name: "Ethan Colish", seats: 2 },
{ name: "Rayyan Qazi", seats: 2 },
{ name: "Alessondra Hopman", seats: 2 },
{ name: "Harrison Fox", seats: 1 },
{ name: "Lenny & Diane", seats: 2 },
{ name: "Karen Shankman", seats: 1 },
{ name: "Patrick Falso & Matt Mika", seats: 2 },
{ name: "The Gikas/Schneewind Family", seats: 5 },
{ name: "Steven Lipton & Sunny Otake", seats: 2 },
{ name: "Sarah Cohen", seats: 1 },
{ name: "The McCormack Family", seats: 4 },
{ name: "Isaac & Edna Browne", seats: 2 },
{ name: "Mary Jo & Michaelene Marchetta", seats: 2 },
{ name: "Ellen & Ira Mirochnick", seats: 2 },
{ name: "Julie & Tony Sherman", seats: 2 },
{ name: "Francisco & Faith Torres", seats: 2 },
{ name: "The Hemphill Family", seats: 3 },
{ name: "Lynda Levin", seats: 1 },
{ name: "Stewart Lipton & Fay Dennen", seats: 2 },
{ name: "The Ettel Family", seats: 3 },
{ name: "Cheri & Durand Tessier", seats: 2 },
{ name: "The Wofse Family", seats: 4 },
{ name: "Chris White & Patrick Langevin", seats: 2 },
{ name: "The Baker Family", seats: 4 },
{ name: "The Fogelman Family", seats: 4 },
{ name: "The Dooley-Monical Family", seats: 4 },
{ name: "Lisa Pickell", seats: 1 },
{ name: "Deckard Johnson", seats: 1 },
{ name: "Bailey and Daniel", seats: 2 },
{ name: "Nivia Diaz and Sam Justiniano", seats: 2 },
{ name: "Jeff & Patrick", seats: 2 },
{ name: "Nico Parker", seats: 1 },
{ name: "James Hemphill", seats: 2 },
{ name: "Hayden Trice", seats: 2 },
{ name: "Nick Vetere", seats: 1 },
{ name: "Veronica Ettel", seats: 1 },
{ name: "George Ettel", seats: 1 },
{ name: "Austin & Mia Catarello Bowlin", seats: 2 },
{ name: "Maxine & Nelson Wofse", seats: 2 },
{ name: "April, Jacob & Matthew Martin", seats: 3 },
{ name: "Chris Ettel & Brittany", seats: 2 },
{ name: "Brenton & Kylee Ettel", seats: 2 },
{ name: "Abbey Sparks", seats: 1 },
{ name: "Josh Tessier", seats: 1 },
{ name: "Herb & Bern Odyniec", seats: 2 },
{ name: "Aggie & Jack Schultz", seats: 2 },
{ name: "Wallace & Sarah Ettel", seats: 2 },
{ name: "MaryAnn & Tom Bryda", seats: 2 },
{ name: "Bernie & Frannie Karol", seats: 2 },
{ name: "Pat Ettel & Cherie Harris", seats: 2 },
{ name: "John, John Jr & Rachael Strider Levi", seats: 3 },
{ name: "Quintin Lasky", seats: 1 },
{ name: "Talia Lasky", seats: 1 },
{ name: "Meg Karol", seats: 1 },
{ name: "Charlotte Karol", seats: 1 },
{ name: "Beth & Mike Fahey", seats: 2 },
{ name: "Nancy Sifuentes & Partner", seats: 2 },
{ name: "Trina Harold & Partner", seats: 2 },
{ name: "Sam McQuiston", seats: 1 },
{ name: "Jenna Wilder", seats: 1 },
{ name: "Katelyn Snider & Liz Sutton", seats: 2 },
{ name: "Brielle Johnson", seats: 1 },
{ name: "Joshua Songster", seats: 1 },
{ name: "Rookery Bean", seats: 1 },
{ name: "Nico LoSauro", seats: 1 },
{ name: "Zelda Goldin", seats: 1 },
{ name: "Beth Sher", seats: 2},
];
